persephone/builds/urls.py
from django.urls import path

from builds import views

app_name = 'builds'

urlpatterns = [
    path('', views.index, name='index'),
    path('global-settings', views.global_settings, name='global_settings'),
    path('domain-not-allowed', views.domain_not_allowed, name='domain_not_allowed'),
    path('projects/create', views.ProjectCreate.as_view(), name='project_create'),
    path('projects/<int:project_id>/', views.project, name='project'),
    path('projects/<int:pk>/delete', views.ProjectDelete.as_view(), name='project_delete'),
    path('projects/<int:pk>/edit', views.ProjectUpdate.as_view(), name='project_update'),
    path('projects/<int:project_id>/builds/<int:build_id>/', views.build_detail, name='build'),
    path('projects/<int:project_id>/builds/<int:build_id>/delete', views.build_delete, name='build_delete'),
    path('projects/<int:project_id>/builds/<int:build_id>/approve',
        views.build_action('approve'), name='build_approve'),
    path('projects/<int:project_id>/builds/<int:build_id>/reject',
        views.build_action('reject'), name='build_reject'),
    path('projects/<int:project_id>/builds/<int:build_id>/screenshots/<int:screenshot_id>/image',
        views.screenshot_image, name='screenshot_image'),
    path('projects/<int:project_id>/builds/<int:build_id>/screenshots/<int:screenshot_id>/diff',
        views.screenshot_image_diff, name='screenshot_image_diff'),

    path('api/v1/projects/', views.APIProjects.as_view(), name='api_projects'),
    path('api/v1/projects/<int:pk>/', views.APIProjectDetail.as_view(), name='api_project'),
    path('api/v1/projects/<int:project_id>/builds/',
        views.APIBuilds.as_view(), name='api_builds'),
    path('api/v1/projects/<int:project_id>/builds/<int:build_id>/',
        views.APIBuildDetail.as_view(), name='api_build'),
    path('api/v1/projects/<int:project_id>/builds/<int:build_id>/finish',
        views.APIBuildFinish.as_view(), name='api_build_finish'),
    path('api/v1/projects/<int:project_id>/builds/<int:build_id>/fail',
        views.APIBuildFail.as_view(), name='api_build_fail'),
    path('api/v1/projects/<int:project_id>/builds/<int:build_id>/screenshots/',
        views.APIScreenshots.as_view(), name='api_build'),
    path('api/v1/projects/<int:project_id>/builds/<int:build_id>/screenshots/<str:screenshot_name>',
        views.APIScreenshotDetail.as_view(), name='api_build'),
]

persephone/persephone/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('builds.urls', namespace='builds')),
]

persephone/builds/models.py
import json
import urllib.parse
from collections import OrderedDict

from django.core.files.base import ContentFile
from django.db import models
from django.db.models.query_utils import Q
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django.urls.base import reverse
from django.utils import timezone
from django.utils.functional import cached_property
from github.MainClass import Github
from wand.image import Image


class GlobalSettings(models.Model):
    google_login_enabled = models.BooleanField(default=False)
    google_whitelist = models.TextField(null=True, blank=True)

    @classmethod
    def get(cls):
        try:
            return cls.objects.get()
        except GlobalSettings.DoesNotExist:
            return cls.objects.create()


class Project(models.Model):
    name = models.CharField(
        max_length=128,
        help_text='Name for your project - used for display purposes.',
    )
    public_endpoint = models.CharField(
        max_length=255,
        help_text='An absolute URL to this website - used for constructing URLs to builds.',
    )
    github_repo_name = models.CharField(
        max_length=128,
        help_text='owner/repo of the GitHub project.',
    )
    github_api_key = models.CharField(max_length=128, help_text='A GitHub access token.')
    auto_archive_no_diff_builds = models.BooleanField(default=True)
    auto_approve_master_builds = models.BooleanField(default=True)
    max_master_builds_to_keep = models.IntegerField(default=20)
    max_branch_builds_to_keep = models.IntegerField(default=20)
    supersede_same_branch_builds = models.BooleanField(default=True)

    @cached_property
    def github(self):
        return Github(login_or_token=self.github_api_key)

    @cached_property
    def github_repo(self):
        return self.github.get_repo(self.github_repo_name)

    def build_absolute_uri(self, uri):
        return urllib.parse.urljoin(self.public_endpoint, uri)

    def archive_old_builds(self):
        unarchived = self.builds.filter(archived=False).order_by('date_started')
        while True:
            master_builds = unarchived.filter(
                Q(branch_name=None) | Q(branch_name__in=['', 'master', 'origin/master']))
            if master_builds.count() <= self.max_master_builds_to_keep:
                break
            build = master_builds.first()
            build.archive()
            build.save()
        while True:
            branch_builds = unarchived.exclude(
                Q(branch_name=None) | Q(branch_name__in=['', 'master', 'origin/master']))
            if branch_builds.count() <= self.max_branch_builds_to_keep:
                break
            build = branch_builds.first()
            build.archive()
            build.save()

    def get_master_baseline(self):
        builds = self.builds.filter(
            Q(state=Build.STATE_APPROVED, archived=False)
            &
            (Q(branch_name=None) | Q(branch_name__in=Build.MASTER_BRANCH_NAMES))
        )
        return builds.filter(date_finished__isnull=False).order_by('-date_started').first()

    class Meta:
        ordering = ('name',)


class Build(models.Model):
    MASTER_BRANCH_NAMES = ['', 'master', 'origin/master']

    STATE_INITIALIZING = 0
    STATE_RUNNING = 1
    STATE_FINISHING = 2
    STATE_PENDING_REVIEW = 3
    STATE_NO_DIFF = 4
    STATE_APPROVED = 5
    STATE_REJECTED = 6
    STATE_FAILED = 7
    STATE_SUPERSEDED = 8
    STATE_FAILING = 9
    STATE_CHOICES = (
        (STATE_INITIALIZING, 'Initializing'),
        (STATE_RUNNING, 'Running'),
        (STATE_FINISHING, 'Finishing'),
        (STATE_PENDING_REVIEW, 'Pending Review'),
        (STATE_NO_DIFF, 'No Diff'),
        (STATE_APPROVED, 'Approved'),
        (STATE_REJECTED, 'Rejected'),
        (STATE_FAILED, 'Failed'),
        (STATE_SUPERSEDED, 'Superseded'),
        (STATE_FAILING, 'Failing'),
    )

    project = models.ForeignKey(Project, models.CASCADE, related_name='builds')
    parent = models.ForeignKey('self', models.SET_NULL, null=True, related_name='children')
    state = models.IntegerField(choices=STATE_CHOICES, default=STATE_INITIALIZING)
    original_build_number = models.CharField(max_length=64, blank=True, null=True)
    original_build_url = models.CharField(max_length=256, blank=True, null=True)
    date_started = models.DateTimeField(default=timezone.now)
    date_finished = models.DateTimeField(null=True)
    date_approved = models.DateTimeField(null=True)
    date_rejected = models.DateTimeField(null=True)
    reviewed_by = models.CharField(max_length=128, blank=True, null=True)
    branch_name = models.CharField(max_length=128, blank=True, null=True, db_index=True)
    pull_request_id = models.CharField(max_length=16, blank=True, null=True)
    commit_hash = models.CharField(max_length=64, blank=True, null=True, db_index=True)
    archived = models.BooleanField(default=False, db_index=True)

    @cached_property
    def github_commit(self):
        return self.project.github_repo.get_commit(self.commit_hash)

    @cached_property
    def github_pull_request(self):
        return self.project.github_repo.get_pull(int(self.pull_request_id))

    def update_github_status(self):
        if not self.commit_hash:
            return
        kwargs = {
            'state': {
                Build.STATE_INITIALIZING: 'pending',
                Build.STATE_RUNNING: 'pending',
                Build.STATE_FINISHING: 'finishing',
                Build.STATE_PENDING_REVIEW: 'pending',
                Build.STATE_NO_DIFF: 'success',
                Build.STATE_APPROVED: 'success',
                Build.STATE_REJECTED: 'failure',
                Build.STATE_FAILING: 'error',
                Build.STATE_FAILED: 'error',
            }[self.state],
            'description': {
                Build.STATE_INITIALIZING: 'Build is initializing.',
                Build.STATE_RUNNING: 'Build is running.',
                Build.STATE_FINISHING: 'Build is finishing.',
                Build.STATE_PENDING_REVIEW: 'Visual diff is pending review.',
                Build.STATE_NO_DIFF: 'There are no visual differences detected.',
                Build.STATE_APPROVED: 'Visual diff is approved.',
                Build.STATE_REJECTED: 'Visual diff is rejected.',
                Build.STATE_FAILING: 'Build is failing.',
                Build.STATE_FAILED: 'Build failed.',
            }[self.state],
            'context': 'persephone',
        }
        if self.project.public_endpoint:
            url = self.project.build_absolute_uri(reverse(
                'builds:build', args=(self.project_id, self.id)))
            kwargs['target_url'] = url
        self.github_commit.create_status(**kwargs)

    def find_parent(self):
        if self.pull_request_id:
            pr_build = Build.objects.filter(
                commit_hash=self.github_pull_request.base.sha,
                date_finished__isnull=False,
                archived=False,
            ).order_by('-date_started').first()
            if pr_build is not None:
                return pr_build
        return self.project.get_master_baseline()

    def _finish_compute_state(self):
        if all(s.state == Screenshot.STATE_MATCHING for s in self.screenshots.all()):
            self.state = Build.STATE_NO_DIFF
            return

        is_master = self.branch_name in Build.MASTER_BRANCH_NAMES
        if is_master and self.project.auto_approve_master_builds:
            self.state = Build.STATE_APPROVED
            self.reviewed_by = 'autoapprover'
            return

        self.state = Build.STATE_PENDING_REVIEW

    def finish(self):
        screenshot_names = {s.name.lower() for s in self.screenshots.all()}
        if self.parent:
            parent_screenshots_map = {
                s.name.lower(): s for s in
                self.parent.screenshots.exclude(state=Screenshot.STATE_DELETED)
            }
            for parent_name, parent_screenshot in parent_screenshots_map.items():
                if parent_name not in screenshot_names:
                    Screenshot.objects.create(
                        build=self,
                        state=Screenshot.STATE_DELETED,
                        parent=parent_screenshot,
                        name=parent_screenshot.name,
                    )
        self._finish_compute_state()
        if self.state == Build.STATE_NO_DIFF:
            if self.project.auto_archive_no_diff_builds:
                self.archive()
        self.date_finished = timezone.now()
        self.update_github_status()

    def fail(self):
        self.state = Build.STATE_FAILED
        self.update_github_status()

    def archive(self):
        for screenshot in self.screenshots.filter(archived=False):
            screenshot.archive()
            screenshot.save()
        self.archived = True

    @cached_property
    def screenshots_by_color(self):
        screenshots = list(self.screenshots.all())
        total_expected = max(1, len(screenshots))
        if self.parent:
            total_expected = max(total_expected, self.parent.screenshots.count())
        return OrderedDict((
            ('success',
             len([s for s in screenshots if
                  s.state == Screenshot.STATE_MATCHING]) / total_expected),
            ('danger',
             len([s for s in screenshots if s.state in [
                 Screenshot.STATE_DELETED, Screenshot.STATE_DIFFERENT]]) / total_expected),
            ('warning',
             len([s for s in screenshots if s.state == Screenshot.STATE_PENDING]) / total_expected),
            ('active',
             len([s for s in screenshots if s.state == Screenshot.STATE_NEW]) / total_expected),
        ))

    def supersede(self):
        self.state = Build.STATE_SUPERSEDED

    class Meta:
        ordering = ('-date_started',)


class Screenshot(models.Model):
    DIFF_EPSILON = 1e-4

    STATE_PENDING = 0
    STATE_MATCHING = 1

persephone/builds/forms.py
from allauth.socialaccount.models import SocialApp
from allauth.socialaccount.providers.google.provider import GoogleProvider
from django import forms
from django.contrib.sites.shortcuts import get_current_site

from builds.models import GlobalSettings


class GlobalSettingsForm(forms.Form):
    google_login_enabled = forms.BooleanField(required=False)
    google_client_id = forms.CharField(required=False)
    google_client_secret = forms.CharField(widget=forms.PasswordInput(render_value=True))
    google_whitelist = forms.CharField(required=False)

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.request = request
        settings = GlobalSettings.get()
        self.fields['google_login_enabled'].initial = settings.google_login_enabled
        self.fields['google_whitelist'].initial = settings.google_whitelist
        try:
            social_app = SocialApp.objects.get_current(GoogleProvider.id, self.request)
            self.fields['google_client_id'].initial = social_app.client_id
            self.fields['google_client_secret'].initial = social_app.secret
        except SocialApp.DoesNotExist:
            pass

    def save(self):
        settings = GlobalSettings.get()
        settings.google_login_enabled = self.cleaned_data['google_login_enabled']
        settings.google_whitelist = self.cleaned_data['google_whitelist']
        settings.save()

        if self.cleaned_data['google_client_id'] or self.cleaned_data['google_client_secret']:
            try:
                social_app = SocialApp.objects.get_current(GoogleProvider.id, self.request)
            except SocialApp.DoesNotExist:
                social_app = SocialApp.objects.create(
                    name=GoogleProvider.name,
                    provider=GoogleProvider.id,
                )
                site = get_current_site(self.request)
                social_app.sites.add(site)
            social_app.client_id = self.cleaned_data['google_client_id']
            social_app.secret = self.cleaned_data['google_client_secret']
            social_app.save()

persephone/builds/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'persephone/main.css' %}" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
    <script src="{% static 'elevatezoom-master/jquery.elevateZoom-3.0.8.min.js' %}"></script>

    <script src="{% static 'persephone/main.js' %}"></script>
</head>
<body>
<div class="container-fluid">
    {% block container %}{% endblock %}
</div>

{% block body_end %}{% endblock %}
</body>
</html>

persephone/builds/templates/build.html
{% extends 'page.html' %}
{% load builds_filters humanize %}

{% block container %}
    {{ block.super }}

    <div class="row">
        <div class="col-md-12">
            <div class="well">
                <div class="pull-right">
                    <div class="dropdown dropdown-inline">
                        <button type="button" class="btn btn-default" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'builds:build_delete' build.project_id build.id %}"
                                   data-action="confirm-post"
                                   data-csrf-token="{{ csrf_token }}">
                                    Delete Build
                                </a>
                            </li>
                            {% if build.state == build.STATE_REJECTED %}
                                <li>
                                    <a href="{% url 'builds:build_approve' build.project_id build.id %}"
                                       data-action="post" data-csrf-token="{{ csrf_token }}">
                                        Approve
                                    </a>
                                </li>
                            {% elif build.state == build.STATE_APPROVED %}
                                <li>
                                    <a href="{% url 'builds:build_reject' build.project_id build.id %}"
                                       data-action="post" data-csrf-token="{{ csrf_token }}">
                                        Reject
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>

                    <a href="{% url 'builds:project' build.project_id %}" class="btn btn-primary">
                        View Project
                    </a>

                    {% if build.state == build.STATE_PENDING_REVIEW %}
                        <a href="{% url 'builds:build_approve' build.project_id build.id %}"
                           data-action="post" data-csrf-token="{{ csrf_token }}"
                           class="btn btn-success">
                            Approve
                        </a>
                        <a href="{% url 'builds:build_reject' build.project_id build.id %}"
                           data-action="post" data-csrf-token="{{ csrf_token }}"
                           class="btn btn-danger">
                            Reject
                        </a>
                    {% endif %}
                </div>

                <h3>
                    {{ build.id }}
                    {% with build.original_build_url as url %}
                        (<a href="{% if url %}{{ url }}{% endif %}">CI
                        #{{ build.original_build_number }}
                        <small><span
                                class="glyphicon glyphicon-new-window" aria-hidden="true"></span>
                        </small>
                    </a>)
                    {% endwith %}
                    {% if build.archived %}
                        <span class="glyphicon glyphicon-compressed" aria-hidden="true"></span>
                    {% endif %}
                </h3>
                <h4>
                    {{ build.branch_name }}
                    <a href="https://github.com/{{ build.project.github_repo_name }}/commit/{{ build.commit_hash }}">
                        {{ build.commit_hash }}
                        <small><span
                                class="glyphicon glyphicon-new-window" aria-hidden="true"></span>
                        </small>
                    </a>
                </h4>
                <h4>
                    {% if build.pull_request_id %}
                        Pull Request:
                        <a href="https://github.com/{{ build.project.github_repo_name }}/pull/{{ build.pull_request_id }}">
                            #{{ build.pull_request_id }}</a>
                        <br>
                    {% endif %}
                </h4>
                <h4>State: {{ build.get_state_display }}</h4>
                Started:
                <span class="subtle-underline"
                      data-toggle="tooltip"
                      title="{{ build.date_started }}">
                    {{ build.date_started|naturaltime }}
                </span>
                <br>
                {% if build.date_finished %}
                    Finished:
                    <span class="subtle-underline"
                          data-toggle="tooltip"
                          title="{{ build.date_finished }}">
                        {{ build.date_finished|naturaltime }}
                    </span>
                    <br>
                {% endif %}
                {% if build.date_approved %}
                    Approved:
                    <span class="subtle-underline"
                          data-toggle="tooltip"
                          title="{{ build.date_approved }}">
                        {{ build.date_approved|naturaltime }}
                    </span>
                    <br>
                {% endif %}
                {% if build.date_rejected %}
                    Rejected:
                    <span class="subtle-underline"
                          data-toggle="tooltip"
                          title="{{ build.date_rejected }}">
                        {{ build.date_rejected|naturaltime }}
                    </span>
                    <br>
                {% endif %}
                {% if build.reviewed_by %}
                    Reviewed by: {{ build.reviewed_by }}<br>
                {% endif %}
                Baseline:
                {% if build.parent %}
                    <a href="{% url 'builds:build' build.parent.project_id build.parent.id %}">
                        {{ build.parent.branch_name }} / {{ build.parent.commit_hash }}
                        ({{ build.parent.date_started }})
                    </a>
                {% else %}
                    no baseline
                {% endif %}

                {% if build.screenshots_by_color %}
                    {% include 'partials/_build_progress_bar.html' %}
                {% endif %}
            </div>
        </div>
    </div>

    {% for screenshot in screenshots %}
        <div class="row {% if screenshot.state == screenshot.STATE_MATCHING %}collapsed-screenshot{% endif %}">
            <div class="col-md-12">
                <div class="panel panel-default panel-diff">
                    <div class="panel-heading screenshot-panel-heading">
                        {{ screenshot.name }}
                        ({{ screenshot.get_state_display }}{% if screenshot.image_diff_amount %}
                        {{ screenshot.image_diff_amount }}{% endif %})
                        {% if screenshot.metadata.console_log %}
                            <button class="screenshot-console-button" data-metadata-json="{{ screenshot.metadata_json }}">
                                <i class="glyphicon glyphicon-list"></i>
                            </button>
                        {% endif %}
                    </div>
                    <div class="panel-body">
                        <div class="image image-parent">
                            {% if screenshot.parent.image %}
                                {% url 'builds:screenshot_image' build.parent.project_id build.parent.id screenshot.parent.id as image %}
                                <img src="{{ image }}">
                            {% endif %}
                        </div>
                        <div class="image image-diff">
                            {% if screenshot.image_diff %}
                                {% url 'builds:screenshot_image_diff' build.project_id build.id screenshot.id as image %}
                                <img src="{{ image }}">
                            {% endif %}
                        </div>
                        <div class="image image-current">
                            {% if screenshot.image %}
                                {% url 'builds:screenshot_image' build.project_id build.id screenshot.id as image %}
                                <img src="{{ image }}">
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

    {% if num_matching %}
        <div class="row uncollapse-screenshots">
            <div class="col-md-12">
                <div class="well text-center">
                    <button type="button" class="btn btn-primary">
                        View {{ num_matching }} collapsed matching screenshots
                    </button>
                </div>
            </div>
        </div>
    {% endif %}

    <script type="text/javascript">
        $(function() {
            $('.panel-body .image img').elevateZoom({
                zoomType: 'inner',
                cursor: 'crosshair'
            });
            $('.uncollapse-screenshots').click(function() {
                $('.uncollapse-screenshots').hide();
                $('.collapsed-screenshot').slideDown();
            })
        })
    </script>

    <div class="screenshot-console-modal-background">
        <div class="screenshot-console-modal">
            <div class="screenshot-console-modal-inner-container">
                <h2 class="screenshot-console-modal-title">Console Messages</h2>
                <button type="button" class="close screenshot-console-modal-close-button" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <div class="screenshot-console-entries"></div>
            </div>
        </div>
    </div>

    <script>  
        $('.screenshot-console-button').click(function() {
            const $entries = $(".screenshot-console-entries");
            $entries.empty();
            for (const entry of $(this).data("metadata-json").console_log) { 
                const date = new Date(entry.timestamp);   
                const formattedTimestamp = `${date.getFullYear()}/${date.getMonth()}/${date.getDate()} ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}`;
                $entries.append(
                    $("<div>")
                        .addClass(`screenshot-console-entry console-entry-${entry.level.toLowerCase()}`)
                        .text(`${formattedTimestamp} ${entry.level}: ${entry.message}`)
                );
            }
            $('.screenshot-console-modal-background').addClass('modal-open');
            $('html, body').css({
                overflow: 'hidden',
            });
        })
        
        $('.screenshot-console-modal-close-button').click(function(e) {
            $('.screenshot-console-modal-background').removeClass('modal-open');
            $('html, body').css({
                overflow: 'auto',
            });
        })
    </script>
{% endblock %}

{% block body_end %}
    <div class="screenshot-console-modal-background">
        <div class="screenshot-console-modal">
            <div class="screenshot-console-modal-inner-container">
                <h2 class="screenshot-console-modal-title">Console Messages</h2>
                <button type="button" class="close screenshot-console-modal-close-button" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <div class="screenshot-console-entries"></div>
            </div>
        </div>
    </div>
{% endblock %}

persephone/builds/templates/index.html
{% extends 'page.html' %}

{% block container %}
    {{ block.super }}

    <div class="row">
        <div class="col-md-12">
            <div class="well">
                <div class="row project-list">
                    {% for project in projects %}
                        <div class="col-md-3">
                            <a href="{% url 'builds:project' project.id %}" class="thumbnail">
                                <div class="caption">
                                    <h2>{{ project.name }}</h2>
                                    <h4>
                                        <strong>Project ID</strong><br>
                                        {{ project.id }}<br>
                                        <strong>GitHub Repo</strong><br>
                                        {{ project.github_repo_name }}<br>
                                        <strong>Public URL</strong><br>
                                        {{ project.public_endpoint }}<br>
                                    </h4>
                                </div>
                            </a>
                        </div>
                    {% endfor %}

                    <div class="col-md-3">
                        <a href="{% url 'builds:project_create' %}" class="thumbnail add-project">
                            <div class="caption">
                                <h2 class="text-center">Create Project</h2>
                                <h1 class="text-center">
                                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                                </h1>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

persephone/builds/templates/page.html
{% extends 'base.html' %}
{% load static builds_filters %}

{% block container %}
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <ul class="nav navbar-nav">
                {% url 'builds:index' as url %}

                <a class="navbar-brand" href="{{ url }}">
                    <img alt="Logo" src="{% static 'persephone/../../assets/img/logo.svg' %}">
                </a>

                <li class="{% if request.path == url %}active{% endif %}">
                    <a href="{{ url }}">
                        Dashboard
                    </a>
                </li>

                {% for project in projects %}
                    {% url 'builds:project' project.id as url %}
                    <li class="{% if request.path|startswith:url %}active{% endif %}">
                        <a href="{{ url }}">
                            {{ project.name }}
                        </a>
                    </li>
                {% endfor %}

                {% url 'builds:global_settings' as url %}
                <li class="{% if request.path == url %}active{% endif %}">
                    <a href="{{ url }}">
                        Settings
                    </a>
                </li>

                {% url 'admin:index' as url %}
                <li class="{% if request.path == url %}active{% endif %}">
                    <a href="{{ url }}">
                        Admin
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li>
                    <p class="navbar-text">
                        {% if request.user.first_name or request.user.last_name %}
                            {{ request.user.first_name }} {{ request.user.last_name }}
                        {% elif request.user.email %}
                            {{ request.user.email }}
                        {% else %}
                            {{ request.user.username }}
                        {% endif %}
                    </p>
                </li>

                <li>
                    <a href="{% url 'account_logout' %}" data-action="post"
                       data-csrf-token="{{ csrf_token }}">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
{% endblock %}